### ISSUE TITLE
Crash on Extracting Data (Update)

### ISSUE THREAD

**Issue by Matt-Power** [Bruker-Amics/bugs_features#220]
This has been logged in different ways several times but it is still a significant issue that is delaying several of my projects.

Regardless of using block or granular measurements, large images of fine grained rocks causes a crash when switching to the calculation tables (memory runs up until if finally gives up and crashes - briefly taking the OS with it). A slight work around is by switching to the frame layer and then clicking on the calculations tab. It's still super slow but doesn't crash so often. However, the batch data extraction for the Frame layer does not work.

This all seems to stem from the fact that all grain data is calculated to construct the data table, even if only simple pixel count type data such as modal or density data is required. I rarely use the grain data and especially in block mode so happy to forego those and associated columns (or have an option to ignore / not calculate those).

I have several projects with measurements that are virtually inaccessible and substantially delayed due to this issue.

**Comment by GGloy** [comment]
@Matt-Power I assume this issue has been resolved and just never closed. Can you please let me know?

**Comment by Matt-Power** [comment]
I believe it is still there. I haven't run any large measurements recently so not 100% but I still get regular crashes due to memory handling.

**Comment by GGloy** [comment]
Thanks Matt, will leave this open.

**Comment by ChiLyMan** [comment]
@Matt-Power Can you define "large" images? I've tried on the largest test project I have which is a block matrix map about 150MB and I don't see this issue on 3.3.0.1537.

**Comment by Matt-Power** [comment]
I think it depends on how much memory you have (I've just increased to 32Gb so see it less). Images that often give me issues have an MRE file in excess of 100Mb but the associated files are well over 1Gb. It tends to happen when I switch from the sample viewing pane to the calculation tables - it just sits there churning through data until it runs out of memory. Happens with very much smaller measurements too (had some with 1.5M Xray points that was taking an age to calculate).

**Comment by ChiLyMan** [comment]
@Matt-Power Have you seen this happen recently on 3.3.0.1508? I'm running a few builds later version (1537) and monitoring the CPU/RAM when processing a 150MB MRE (total project size of ~1.2GB) I no longer see a large movement on memory usage, with about 1GB being consumed, and not much extra when moving from Sample Image to Calculation Tables.
