### ISSUE TITLE
Bug - Process - Mineral Size Distribution Not Working

### ISSUE THREAD

**Issue by scarlett-01110011** [Bruker-Amics/bugs_features#435]
Mineral size distribution on the calculations tab is not working. 
All size data is missing, including retained wt%, cumulative passing wt%, particle counts.
Only the P-table is displayed but always with the same value.

Changing the grouping or mineral of interest does not change the outputs.

AMICS version 3.3.0.1903

![image](https://github.com/Bruker-Amics/bugs_features/assets/117055041/45b39f00-3701-4afe-86b6-acd186d2ec9e)

**Comment by MarkGuo7** [comment]
Sorry Scarlett

This should be fixed in the latest version. I will send you one this afternoon, after fixing the clean-up unxray issue.

**Comment by MarkGuo7** [comment]
Here is the latest one. Please give it a try when you have time.

https://bruker-my.sharepoint.com/:u:/p/junfeng_guo/EYjLvIlgCUtEtaDcSNqoOYkBljESGQ_owSFCqAEjZiggFw?e=Ut0dIr

**Comment by ChiLyMan** [comment]
Mineral Size Distribution is working in vs1983, but the P80, P50 and P20 labels are still missing.
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBbmVZIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--c817a8e4b7ff7f2b9e57c9bd40dc688405ee1636/image.png)

**Comment by GGloy** [comment]
@ChiLyMan This is a strange one, still fine on mine.
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBaGFhIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--cf6b61fe781e03a11cf8ad15eda4630ae7ba4495/image.png)

**Comment by ChiLyMan** [comment]
Just tested on 3.2.0.270 and P-values are shwoing:-
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeGFBQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--5ec5097f1d34525bbbf657e19a1c9970cd0af34e/image.png)

But in 3.3.0.1701 and 3.3.0.1996, P-values do not show:-
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeG1BQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--65293c3e8e824c8e9a648e8eb4d18ef5b5ab6555/image.png)

**Comment by jonathan-knapp** [comment]
@ChiLyMan is this fixeD?
