### ISSUE TITLE
Calc. Tables do not accept changing group of minerals

### ISSUE THREAD

**Issue by PMC-Labs** [Bruker-Amics/bugs_features#541]
when I try to select material it defaults to either the first mineral in the grouping or allows selection only of single mineral id(ungrouped)

![Image](https://github.com/user-attachments/assets/3d09f793-c449-41ac-8cc4-dc94157a06cb)

**Comment by PMC-Labs** [comment]
This is version 3.4.1.1385
and 5.1 as well

**Comment by AlexeiDolgolyov** [comment]
I think it's already fixed in actual version.

**Comment by PMC-Labs** [comment]
Not Fixed, completely when I select a mineral I can see the new data but when I do a batch calculation the data is from the first mineral in the group.

@ChiLyMan

**Comment by ChiLyMan** [comment]
@AlexeiDolgolyov More detail for you:-
In Process now the table is showing the data correctly:-
<img width="1476" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNGtuQ2c9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--f0a8feb87164e425212429006aa82355dd1bdf52/image.png" alt="image.png" />

But when we use the Batch Calculation option:-
<img width="1476" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNG9uQ2c9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--f7462932bf118d3c923b047597d599d012078766/image.png" alt="image.png" />

1) There is no option to change the material, so we would assume the currently selected Material would be the target (i.e. Magnetite).
2) But in fact the Batch Calculation export will just use the first item on the list. In the Primary Table it will use the first mineral, in the group table it will use the first item in the group:-
<img width="1488" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNHNuQ2c9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--02a5b7f9183fd75601539822e1adae3548c3746b/image.png" alt="image.png" />

**Comment by AlexeiDolgolyov** [comment]
@ChiLyMan , thanks for the clarification. Will fix the issue.

**Comment by vfishbain** [comment]
Fixed

**Comment by ChiLyMan** [comment]
Fixed in 5.1.1
